### ISSUE TITLE
Error while updating status

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/ofdb-cli#5]
Fehler beim Import neuer Stati

![grafik](https://user-images.githubusercontent.com/15019030/159716463-519bf039-dece-462b-8343-423953e22b98.png)

**Comment by wellemut** [comment]
fehler lag beim login, laut @flosse 
Jetzt kann es neu versucht werden.

**Comment by wellemut** [comment]
@flosse 
Es gibt immer noch folgende Fehlermeldung

INFO  ofdb > Reas reviews from file: review.csv
 INFO  ofdb_cli::csv > Read reviews form CSV
 INFO  ofdb          > 66 reviews where found in CSV file
 INFO  ofdb_cli      > Try to login with 'helmut@bildungsagenten.com'
 INFO  ofdb          > Review the following place IDs: {
    3c5e5035-33b4-49c7-ae73-4b7d34cf5f6d,
}
 WARN  ofdb          > Unable to review: error decoding response body: expected value at line 1 column 1
 INFO  ofdb          > Review the following place IDs: {
    4175a461-5c90-4d6c-a417-14d15c63f164,

**Comment by flosse** [comment]
I have not received any errors.

**Comment by wellemut** [comment]
probably solved
