### ISSUE TITLE
Force to create new entrie, despite duplicate warning

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/ofdb-cli#6]
While importing a list of entries, I get a few warnings of dupliates back, after importing the list the first time. When I have checked them, some duplicates where indentified wrongly as such and I am sure, thats a unique new entry. How can I force the import of entries, that where identified as duplicates, but are unique new entries?

I want to import a csv in the same format like the first time, but without duplicate checking.

- [ ] Develope and describe the command for this forced import.

Attached a list of 50 unique entries, that caused duplicate warnings: 
[entries unique for import.csv](https://github.com/kartevonmorgen/ofdb-cli/files/11584878/entries.unique.for.import.csv)

**Comment by flosse** [comment]
`--ignore-duplicates` is the new flag you can use:

![Bildschirmfoto vom 2023-07-17 15-18-20](https://github.com/kartevonmorgen/ofdb-cli/assets/276043/7df7923b-464e-4fc0-99cb-556f8b6194d3)

**Comment by wellemut** [comment]
@flosse Richtig genial! Funktioniert perfekt. Ich konnte die ofdb zwingen, 25 Einträge zu fressen, wo es eigenlticht Duplettenwarnungen gabe ;)
