### ISSUE TITLE
Update by merge request

### ISSUE THREAD

**Issue by flosse** [kartevonmorgen/ofdb-cli#9]
Original feature request by @wellemut:

> Quite helpful would be a "merge" command: That would mean, that all fields which are empty in the update-file, stay like it is, and only given fields will be updated in the entry profile. Additional there are the following rules:
> - tags are never replaced but always attached (additionally added)
> - Also new descriptions will allways be added at the beginning, but dont replace existing description.
> 
> All other fields will overwrite the old entry, if given in the update file.

**Comment by flosse** [comment]
We could use a primitive syntax to modify fields like this:
- `++` append
- `--` remove
- `==` replace

All other fields, which should not be changed, (except the ID) have to be empty.

**Comment by wellemut** [comment]
![grafik](https://github.com/kartevonmorgen/ofdb-cli/assets/15019030/8f797a74-b2f4-43ec-aa80-b4ea409567fd)

Folgende idee: also commando nutzt du einfach die --patch option und bei den einzelnen feldern kannst du mit `++`, `--` oder `==` die sachen modifizieren

**Comment by wellemut** [comment]
Hi @flosse 
Also grundsätzlich funktioniert der update prozess.
Wenn ich die Download csv nehme und sie für das Update nutzen will, beschwert er sich, dass 2 spalten fehlen
- `created `(das fehlt heist im download `created_at`)
- `ratings` (heißt im download `avg_rating`)

- [ ] Die anpassung der Spaltenüberschriften für das update ist eine schnelle sache, sollten wir aber vielleicht im script korrigieren.

- [x] Der `--patch` Befehl funktioniert gar nicht.
Bei dem Befehl: `https://api.ofdb.io/v0/ update --patch --report-file update-report.json "update.csv"` kommt dieser Fehler:
![grafik](https://github.com/kartevonmorgen/ofdb-cli/assets/15019030/1da43fb5-d354-4bdf-b481-a1746dc04ca1)

Wenn ich es wegmache, kann ich updaten, dann wird aber alles überschrieben. 
![grafik](https://github.com/kartevonmorgen/ofdb-cli/assets/15019030/d96fd077-6599-4845-a8aa-cfd47074c747)
Du siehst an den ++ dass ich eigentlich nur gewisse Felder überschreiben wollte.

**Comment by wellemut** [comment]
Das script erstellt seit dem 2. import keine report.json, aber vielleicht auch nur, weil es keine fehler gibt.

**Comment by wellemut** [comment]
Die Versionsnummer ist wirklich eine perfekte Kontrolle, dass man nur das katualisieren kann, was man kurz vorher runer geladen hat.
Leider werden aber sämtliche Custom-links einfach weggelöscht. So ist es natürlich echt gefährlich und jemand kann viel arbeit kamputt machen, indem er einfach was runterläd und direkt wieder hoch.

Wenn man gurndsätzlich einstellen könnte, dass wirklich nur die attribute überschrieben werden, wo auch ein wert hochgeladen wrid, könnte man das vielleicht umgehen.

**Comment by wellemut** [comment]
Shit BUG! @flosse 
Nachdem ich nun 500 Einträge upgedatet habe, fällt mir auf, dass die danach von der Karte verschwinden und tauchen auch nicht in der Seitenleiste auf!

Such mal nach Klingspor, da sollten eigentlich über 23 Dupletten angezeigt werden: https://www.kartevonmorgen.org/m/main?c=49.7600%2C9.9316&z=6.00&search=Klingspor+

Das Backend findet sogar noch alles: https://openfairdb.org/search?q=Klingspor+
(auch im neuen https://ofdb.io/)

Aber auf der _Karte ist nichts mehr! Warum?

**Comment by wellemut** [comment]
Ahh, ich habs. Das problem ist das Feld `categories` mit den IDs `77b3c33a92554bcf8e8c2c86cedd6f6f `und `2cd00bebec0c48ba9db761da48678134`
stattdessen muss ich offenbar die Tags `commercial `oder `non-profit` nutzen

**Comment by wellemut** [comment]
Ich habe hier eine beschreibung der nutzung begonnen: https://github.com/kartevonmorgen/ofdb-cli/tree/update-patch-description?tab=readme-ov-file#update-patch-entries-via-csv

**Comment by wellemut** [comment]
@flosse schreibt:
> FYI: Ich habe heute nochmal nen mini update für's CLI gemacht, weil bei mir mit 500 CSV Einträgen es ein Netzwerkfehler gab. Jetzt werden immer nur 50 Einträge auf einmal abgerufen.
Naja, auf jeden Fall war deine Patch CSV schon *fast* richtig. Nur die Titel der Einträge waren ohne Operation deklariert. Also wenn du den Titel verändern willst, einfach ein '=' davor setzen, also "=Neuer Titel" oder das Feld ganz leer lassen, dann heißt es "mach nix"

Leider immernoch die Fehlermeldung:
```
>ofdb --api-url https://api.ofdb.io/v0/ update --patch --report-file update-refill-report.json update-patch.csv
 INFO  ofdb > Update entries from file (CSV): update-patch.csv
 INFO  ofdb_cli::csv > Read entries form CSV
Error: Patch updates are currently not supported for JSON files
```
ich versuche das gerade über folgende csv:


und in der Hilfe steht auch json und csv als mögliche formate...

```
>ofdb update --patch --help
Update entries

Usage: ofdb --api-url <API> update [OPTIONS] <FILE>

Arguments:
  <FILE>  JSON or CSV file with entries

Options:
      --report-file <REPORT_FILE>  File with the update report [default: update-report.json]
      --patch                      use (non-standard) diff syntax to update fields
  -h, --help                       Print help
```

Ich habe heute den ofdb-cli aktualisiert geupdatet. das hat nicht geholfen.

**Comment by wellemut** [comment]
Auch nach dem letzten Update der Quckfixes https://github.com/kartevonmorgen/ofdb-cli/commit/1971fd7309b1cae6a42f6dc0d4afbc3191e7e9ea
kommen folgende Fehlermeldungen:

n= current Version number on kvm

Wenn die Version-Numer im csv = n+1 kommt:

```
>ofdb --api-url https://api.ofdb.io/v0/ update --patch --report-file update-refill-report.json update-patch.csv
 INFO  ofdb > Update entries from file (CSV): update-patch.csv
 INFO  ofdb_cli::csv > Read entries form CSV
 INFO  ofdb_cli::csv > Read current state of all 4 entries
 WARN  ofdb          > Could not update 'Brücker Mühle': The version of the object is invalid
 WARN  ofdb          > Could not update 'Hof Fleckenbühl': The version of the object is invalid
 WARN  ofdb          > Could not update 'Retro Supply Gießen': The version of the object is invalid
 WARN  ofdb          > Could not update 'ida - Ideen Die Anstecken': The version of the object is invalid
```

Mit Versionnumber = n kommt
```
ofdb --api-url https://api.ofdb.io/v0/ update --patch --report-file update-refill-report.json update-patch.csv
 INFO  ofdb > Update entries from file (CSV): update-patch.csv
 INFO  ofdb_cli::csv > Read entries form CSV
 INFO  ofdb_cli::csv > Read current state of all 4 entries
 WARN  ofdb          > 4 csv records contain errors
```
Und im Jason-report steht dann: `error | "Invalid patch request: Invalid entry version"`

![grafik](https://github.com/kartevonmorgen/ofdb-cli/assets/15019030/930bc7e9-a87f-4358-bd33-8404f4a5adbe)

Gibt es da vielleicht ein Widerspruch im Script?

Ich denke richtig wäre, dass man die Version number manuell hoch setzt in der csv: n+1

Aktuelles testfile
[update-patch.csv](https://github.com/kartevonmorgen/ofdb-cli/files/14230402/update-patch.csv)

**Comment by wellemut** [comment]
Markus will correct it, that the script will upcount version number by itself.

**Comment by wellemut** [comment]
@flosse as I understood you, the new FairSync Interface completly replaces the ofDB-cli. Am I right?
- https://github.com/kartevonmorgen/FairSync/issues/17#issuecomment-2462569849
So we don't need to further develop the cli
I will close this issue thoe, as not planned...
